# Generated by Django 4.2.16 on 2024-11-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusubcategory',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='subcategory_covers/'),
        ),
    ]
